apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: kube-system
spec:
  rules:
    - host: whoami.k8s.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
  tls:
    - hosts:
        - whoami.k8s.local
      secretName: traefik-tls-cert